### ISSUE TITLE
Site-wide problems [502 Bad Gateway]

### ISSUE THREAD

**Issue by Purpzie** [larrychristensen/orcpub#141]
It seems the site is having problems handling requests (this is confirmed from https://isitdownorjust.me/orcpub2-com/), which may also be what's causing me to be unable to log in. Clicking the login button does nothing, doesn't even load anything new or tell me that my password or username is incorrect. Sometimes I'll just get an error that the site cannot handle the request at that time.

**Comment by Purpzie** [comment]
This seems to not be a problem anymore, perhaps it was just an outage in something the site uses. But at least keep an eye on it, good luck.

**Comment by sleepaspell** [comment]
Also having the issue. However mine is an HTTP ERROR 503. Had issues today and last week trying to save a character, so I refreshed and couldn't sign back in.
