### ISSUE TITLE
PARTIES

### ISSUE THREAD

**Issue by Jocksy** [larrychristensen/orcpub#144]
The "Parties" option doesn't allow to create a party. 
I tried in Google and Edge.
I wanted to use the parties option in the combat tracker.
Only workaround I can think about is to add new character for everyone in the party and manually add them one by one to the tracker...

![image](https://user-images.githubusercontent.com/43147223/45311873-8d481280-b4f8-11e8-9f27-4026d1725ca1.png)

**Comment by DivertedCircle** [comment]
Parties are created on the Character List page, they are only edited on the parties page.

**Comment by Jocksy** [comment]
Thanks a lot!
