### ISSUE TITLE
Auto Redirects to https

### ISSUE THREAD

**Issue by txaaron** [larrychristensen/orcpub#2]
After starting the server and running the code, the website loads (localhost:3449) but then automatically redirects to https. I've been unable to find where to change the code to prevent this from happening. Anyone have an idea?

**Comment by onefusion** [comment]
I actually found the redirect in core.cljs under web\cljs\orcpub\

Lines 21-24

**Comment by txaaron** [comment]
Ah that worked! Thanks!
