### ISSUE TITLE
Login page has huge uncached image.

### ISSUE THREAD

**Issue by zvodd** [larrychristensen/orcpub#223]
The `div.registration-image` element on the login page:
```
    background-image: url(/image/shutterstock_432001912.jpg);
    background-size: 1200px 800px;
    background-position: -350px 0px;
    background-clip: content-box;
    width: 350px;
    min-height: 600px;
```
This image (`/image/shutterstock_432001912.jpg`) is 8.9MB, I'm not sure why, but it doesn't seem to cache and reloads every time I hit the login page. Header's don't seem to prevent caching, it maybe just too large of a file to be cached by my browser.

Might I suggest replacing with this image (image cropped to visible portion):
`https://i.imgur.com/cgXaW4k.png` (519KB)

And change the CSS to: 

```
    background-image: url(/image/cgXaW4k.png);
    width: 350px;
    min-height: 600px;
```

**Comment by datdamnzotz** [comment]
Already fixed, just not merged with this repo
https://github.com/Orcpub/orcpub/pull/76/commits/c66b96b83d7b2745e16feefbd39ec75e3218efdd
