### ISSUE TITLE
Ioun Stone (Strength) gets Int

### ISSUE THREAD

**Issue by deviljazz** [larrychristensen/orcpub#252]
When i wear an Ioun Stone (Strength), i got +2 int instead of +2 str.

**Comment by codeGlaze** [comment]
This is something we fixed over at the community [fork of this repo](https://github.com/orcpub/orcpub) [Dungeon Master's Vault](https://dungeonmastersvault.com)

Larry no longer actively maintains orcpub2 or this repo.

**Comment by deviljazz** [comment]
Ok, ty.
