### ISSUE TITLE
Investigate using leiningen profiles to avoid having to change `project.clj` for local dev use

### ISSUE THREAD

**Issue by dhleong** [larrychristensen/orcpub#6]
Would be nice not to have to leave an unchanged file dangling all the time. I'm not a leiningen expert, but it ought to be possible to move that repository to a `:prod` profile, and use the different dependencies based on `:dev` vs `:prod`. For what it's worth, I didn't need to do the `register-wagon-factory!` thing.

**Comment by larrychristensen** [comment]
Are you referring to the datomic dependency? If so, yes, that's a good idea. When I was working alone I just had a test database on AWS that I connected to just like the prod database, but that doesn't work for other people.

**Comment by dhleong** [comment]
> Are you referring to the datomic dependency?

Yep! See PR #7
