### ISSUE TITLE
Expertise Points are incorrectly calculated

### ISSUE THREAD

**Issue by ashf** [larrychristensen/orcpub#66]
Skills with expertise aren't correctly calculated

**Comment by DivertedCircle** [comment]
Can you elaborate? What do you expect to see? What are you seeing instead?

**Comment by DivertedCircle** [comment]
Your image did not work.

**Comment by ashf** [comment]
![stats](https://user-images.githubusercontent.com/6597733/40488373-9e7b84c0-5f34-11e8-940c-65a57c234d58.png)

**Comment by DivertedCircle** [comment]
You are not proficient in Perception, you shouldn't even be able to apply Expertise to it yet you have somehow. As such your passive Perception is calculating correctly. What class/subclass/background is giving you expertise in Perception and Stealth?

**Comment by ashf** [comment]
I see.. I thought expertise and proficiency didn't require stacking.

**Comment by DivertedCircle** [comment]
Orcpub really shouldn't even allow you the option to choose untrained skills to apply expertise to.
